### ISSUE TITLE
Kill FFmpeg gracefully

### ISSUE THREAD

**Issue by busla** [Ch00k/ffmpy#10]
How do you suggest that FFmpeg should be killed gracefully from ffmpy? 

This is my function call:
`os.kill([the-pid-of-ffmpeg], signal.SIGKILL)`

That results in:
```
Exiting normally, received signal 15.
Traceback (most recent call last):
  File "xml_test.py", line 174, in <module>
    record_stream(root)
  File "xml_test.py", line 135, in record_stream
    run_ffmpeg(start_time, stop_time, event.find('title'))
  File "xml_test.py", line 106, in run_ffmpeg
    ff_stream.run()
  File "/Users/jon/code/streampimp/venv/lib/python3.5/site-packages/ffmpy.py", line 92, in run
    raise FFRuntimeError(self.cmd, ff_command.returncode, out[0], out[1])
  File "/Users/jon/code/streampimp/venv/lib/python3.5/site-packages/ffmpy.py", line 141, in __init__
    stdout.decode() or '',
AttributeError: 'NoneType' object has no attribute 'decode'
```

**Comment by busla** [comment]
I´m killing the process from another script so obviously ffmpy can´t communicate with FFmpeg since it´s dead, and throws an error :-P

**Comment by Ch00k** [comment]
@busla The exception you see is actually a bug. I've found and already fixed it today, will soon release a new version.

**Comment by busla** [comment]
Beautiful! :smile:

**Comment by busla** [comment]
have you pushed the fix to any of your branches?

**Comment by busla** [comment]
nevermind, fixed it temporarily with an exception. I´ll just have to be patient 😸

**Comment by busla** [comment]
nice, thanks!
