### ISSUE TITLE
how to use FFprobe?

### ISSUE THREAD

**Issue by jgalindov** [Ch00k/ffmpy#12]
Hi, I am new with ffmpy

I use FFprobe in the windows shell console for determine the position of keyframes in the video:

ffprobe -show_frames C:\myuser\documents\myvideo.avi > c:\myuser\documents\myvideodata.txt
(this code make a txt file with info for all keyframes)

How can I use this code with ffmpy in python?

Edit: 
ffmpy version 0.2.1
python 2.7.12

I tried:
```
import ffmpy
ff = ffmpy.FFprobe(inputs={
    '': ('-show_frames C:/myuser/documents/myvideo.avi > c:/myuser/documents/myvideodata.txt')
})
ff.cmd
ff.run()
```
But I get:
FFRuntimeError: `ffprobe -show_frames C:/myuser/documents/myvideo.avi > C:/myuser/documents/myvideodata.txt' exited with status 1

**Comment by Ch00k** [comment]
@jgalindov Try this:
```python
import ffmpy

ff = ffmpy.FFprobe(inputs={'C:/myuser/documents/myvideo.avi': '-show_frames'})
with open('c:/myuser/documents/myvideodata.txt', 'w') as output_file:
    ff.run(stdout=output_file)
```

**Comment by jgalindov** [comment]
Great!
Thanks

**Comment by kellsburg** [comment]
Hi, I am new with ffmpy as well. 
I am getting a similar issue maybe you could help me if you have the time.

import ffmpy

`        test = ffmpy.FFprobe(inputs={outputVideoFile: '-show_frames'})
         with open('C:/Users/akelly/Desktop/Scripting_Tests/Test_Data/output/test.txt', 'w') as out_file:
                test.run(stdout=out_file)`

But I get this error:
                              FFExecutableNotFoundError: Executable 'ffprobe' not found

What am I doing wrong? Sorry I am quite new at using ffmpy or ffmpeg/ffprobe in general.

**Comment by Ch00k** [comment]
@kellsburg Make sure `ffprobe` is in your path. You can also specify the absolute path to `ffprobe` executable like this:
```
test = ffmpy.FFprobe(
    executable='/usr/local/bin/ffprobe',  # adapt this according to your environment
    inputs={outputVideoFile: '-show_frames'}
)
```
