### ISSUE TITLE
communicate() blocks, how to make it non-blocking

### ISSUE THREAD

**Issue by busla** [Ch00k/ffmpy#13]
When running ffmpy in the background I needed to remove the `communicate()` call in https://github.com/Ch00k/ffmpy/blob/master/ffmpy.py#L103.

I think I´m not understanding the subprocess module properly so do you have any suggestions on how to make the subprocess non-blocking?

Cheers.

**Comment by busla** [comment]
see:
https://github.com/busla/ffmpy/commit/0996274c65448cc7c0a8e25c58fa8bd86d497ea2

**Comment by Ch00k** [comment]
@busla Would running ffmpy in a separate thread work for your scenario?

**Comment by busla** [comment]
Yes it would, that´s actually how I implemented my project in the beginning, but soon realised that it was unnecessary.

FFmpy is now run on my class instances and added as a class variable so I can terminate it when I flag my instance to do so.
