### ISSUE TITLE
using -map with overlay

### ISSUE THREAD

**Issue by ghost** [Ch00k/ffmpy#14]
Hey I have this ffmpeg shell script working to overlay a png file, use a color key filter to create a green screen and then overlay the png with an input .mp4 file. 

<img width="490" alt="screen shot 2016-11-21 at 12 30 08 pm" src="https://cloud.githubusercontent.com/assets/12484426/20493328/490628e6-afe6-11e6-9928-db35779438db.png">

I was wondering if you'd be able to tell me how to transfer this command line to your python wrapper. I think I have the hang of most of, from reading the documentation, but I was unable to figure out how to use -map in the way I'm using it in the above screenshot. Thanks!

**Comment by Ch00k** [comment]
@Jakymiw Try this:

```python
inputs = OrderedDict([('input.mp4', None), ('overlay.png', None)])
outputs = {
    'output.mp4': (
        '-filter_complex',
        "[1:v]colorkey=0x00ff00:0.5:00[1v]; [0:v][1v]overlay=enable='between(t,1,5)'[out1]",
        '-map',
        '[out1]'
    )
}
ff = FFmpeg(inputs=inputs, outputs=outputs)

**Comment by Ch00k** [comment]
I'm assuming the above approach worked.
