### ISSUE TITLE
pipe:0: Invalid data found when processing input

### ISSUE THREAD

**Issue by buhuipao** [Ch00k/ffmpy#15]
![image](https://cloud.githubusercontent.com/assets/14309948/21513113/dc16a766-ccef-11e6-9e4d-b43cfc7ae7af.png)
Here is my code:
class MyOutput(object):
    def __init__(self, url):
        self.url = url

    def write(self, buf):
        print('start publish rtmp stream...')
        ff = FFmpeg(inputs={'pipe:0':'-vcodec libx264'}, outputs={self.url:'-r 24 -s 640x480 -f flv'})
        print(ff.cmd)
        ff.run(input_data=buf)
Please help me!  what has happend to me?

**Comment by Ch00k** [comment]
The reason could be that ffmpeg does not understand the data you give it. Could be because the data is not actually a video. Are you sure you read it correctly? You could run the command printed by `print(ff.cmd)` manually to check if that would work.

**Comment by buhuipao** [comment]
Here is the ff.cmd:
    ffmpeg -i pipe:0 -vcodec libx264 -r 24 -s 640x480 -f flv rtmp://apmedia1.livecoding.tv:1935/

**Comment by Ch00k** [comment]
What happens if you run it in your terminal? Does it work?

**Comment by buhuipao** [comment]
And I try ：
class MyOutput(object):
    def __init__(self, url):
        self.url = url

    def write(self, buf):
        cmdline = ['ffmpeg', '-i', '-', '-r', '24', '-vcodec', 'libx264', '-s', '640x480', '-f', 'flv', self.url]
        publisher = subprocess.Popen(cmdline, stdin=subprocess.PIPE)
        print('start publish rtmp stream...')
        publisher.stdin.write(buf)
also have the same error(Invalid data found when processing input ,  "buf" is  an io.Bytesio() type, Look like ffmpeg can't understand the buf.

**Comment by Ch00k** [comment]
@buhuipao ffmpeg needs the data to be raw binary data, e.g. the result of doing `open('/path/to/file', 'b').read()`. Make sure you provide the data in correct format.

**Comment by buhuipao** [comment]
Thank for your response, my little project had worked

**Comment by Ch00k** [comment]
@buhuipao I'm glad it worked!

**Comment by kiriakos15** [comment]
I have the same error how did you make it work?

**Comment by damvantai** [comment]
> And I try ：
> class MyOutput(object):
> def **init**(self, url):
> self.url = url
> 
> ```
> def write(self, buf):
>     cmdline = ['ffmpeg', '-i', '-', '-r', '24', '-vcodec', 'libx264', '-s', '640x480', '-f', 'flv', self.url]
>     publisher = subprocess.Popen(cmdline, stdin=subprocess.PIPE)
>     print('start publish rtmp stream...')
>     publisher.stdin.write(buf)
> ```
> 
> also have the same error(---Invalid data found when processing input---) , "buf" is an io.Bytesio() type, Look like ffmpeg can't understand the buf.

thank you very much!!!

**Comment by mooction** [comment]
Hi everyone, i use this cmdline:
```
ffmpeg -i - -f g722 -ar 16000 -acodec pcm_s16le qqq.wav
```
It goes 
```
pipe:: Invalid data found when processing input
```
Then, I changed the sequence of args like this:
```
ffmpeg -f g722 -i - -ar 16000 -acodec pcm_s16le qqq.wav
```
Now it works. I think this may help someone.

**Comment by AlexanderHindos** [comment]
I use command with streamlink and ffmpeg and all works correct but if I try to run it as bash it show same error
 
>  libavfilter     5. 40.101 /  5. 40.101
>   libavresample   2.  1.  0 /  2.  1.  0
>   libswscale      3.  1.101 /  3.  1.101
>   libswresample   1.  2.101 /  1.  2.101
>   libpostproc    53.  3.100 / 53.  3.100
> pipe:0: Invalid data found when processing input
> 

command: 
> streamlink https://youtu.be/HpZAez2oYsA best -O | ffmpeg -re -i pipe:0 -c copy -f mpegts http://127.0.01/cam_live/mpegts

**Comment by yishengjiang99** [comment]
I got this message with f32le audio, but did not get this message with s16le audio.

very unhelpful message. if the person who wrote it knows what's wrote with our format, why he got play dumbadore and make us guess, why not just tell us?
