### ISSUE TITLE
License

### ISSUE THREAD

**Issue by wchill** [Ch00k/ffmpy#16]
What is the license for this code? I plan on forking it and making it use [`asyncio-subprocess`](https://docs.python.org/3/library/asyncio-subprocess.html) instead of standard `subprocess` as I have a project that necessitates the use of coroutines and I'd rather not introduce multithreading when it isn't necessary.

**Comment by Ch00k** [comment]
@wchill It does not have any license at the moment? Would the absence of a license prevent you from forking? If so I can add something like an MIT license.

**Comment by wchill** [comment]
I plan to publish the revised project on PyPi to make it easier to deploy for my projects that will use it, so something like MIT would be fine.

**Comment by Ch00k** [comment]
Did you consider contributing to this project (e.g. by creating a merge request) instead of forking it?

**Comment by wchill** [comment]
The resulting code would only be compatible with Python 3.5 and is only designed for asynchronous use, so it's not really ideal.
