### ISSUE TITLE
when output file path includes spaces, it does not work. 

### ISSUE THREAD

**Issue by nishantkumarsah** [Ch00k/ffmpy#18]
When there is an space in the absolute path of file name it does not work. 
E.g. "/var/www/etb-xxx-01.info/public_html/downloads/abc@live.com/Pretty Face Blonde /princessa_v_klopovnike.avi_VIRTUAL_FILE_"

Here the space between **"Pretty Face Blonde"** is creating issue.
I checked the same query with no space. It works.

**Comment by Ch00k** [comment]
@nishantkumarsah Thanks for reporting this! I will have a look to see if I can reproduce it.

**Comment by nishantkumarsah** [comment]
Here is the query, if this helps
output_options = "/var/www/etb-xxx-01.info/public_html/downloads/abc@live.com/Pretty Face Blonde /princessa_v_klopovnike.avi_VIRTUAL_FILE_"

ff = ffmpy.FFmpeg(
                          global_options={Constant.FFMPEG_OUTPUT_GLOBAL_OPTIONS},
                          inputs={self.abs_fileName: None},
                          outputs={self.abs_fileName + Constant.VIRTUAL_FILE_IDENTIFIER + '/' + Constant.PLAYLIST_NAME : output_options}
                          )

**Comment by Ch00k** [comment]
@nishantkumarsah Could you also post the error you're getting?

**Comment by nishantkumarsah** [comment]
[NULL @ 0x3854040] Unable to find a suitable output format for 'Blonde'
Blonde: Invalid argument
Traceback (most recent call last):
  File "/var/www/etb-xxx-01.info/webapps/file_operations/convert_file.py", line 94, in <module>
    fc.prepareHLSsegments()
  File "/var/www/etb-xxx-01.info/webapps/file_operations/convert_file.py", line 74, in prepareHLSsegments
    ff.run()
  File "/usr/local/lib/python2.7/dist-packages/ffmpy.py", line 105, in run
    raise FFRuntimeError(self.cmd, self.process.returncode, out[0], out[1])
ffmpy.FFRuntimeError: `ffmpeg -loglevel error -i "/var/www/etb-xxx-01.info/public_html/downloads/abc@live.com/Pretty Face Blonde/princessa_v_klopovnike.avi" -preset ultrafast -hls_time 10 -f hls -hls_list_size 0 -s 480x270 -hls_segment_filename /var/www/etb-xxx-01.info/public_html/downloads/abc@live.com/Pretty Face Blonde/princessa_v_klopovnike.avi_VIRTUAL_FILE_/partial_file%04d.ts "/var/www/etb-xxx-01.info/public_html/downloads/abc@live.com/Pretty Face Blonde/princessa_v_klopovnike.avi_VIRTUAL_FILE_/playlist.m3u8"` exited with status 1

STDOUT:


STDERR:

**Comment by Ch00k** [comment]
I see that the input and output paths are properly handled by subprocess command line compilation, i.e. quoted. The problem is the value of `-hls_segment_filename` option, which also contains spaces. This is not handled by subprocess. As a workaround, try quoting it yourself, like that:
```
output_options = '-preset ultrafast -hls_time 10 -f hls -hls_list_size 0 -s 480x270 -hls_segment_filename "/var/www/etb-xxx-01.info/public_html/downloads/abc@live.com/Pretty Face Blonde/princessa_v_klopovnike.avi_VIRTUAL_FILE_/partial_file%04d.ts"'
```
I'll see what I can do to prevent this kind of failure, when an option value contains spaces.

**Comment by nishantkumarsah** [comment]
ok let me check

**Comment by nishantkumarsah** [comment]
ok. i did this and it worked.
output_options  =   Constant.FFMPEG_OUTPUT_CODEC_HLS_NOT_SUPPORTED + '"{}"'.format(self.abs_fileName + Constant.VIRTUAL_FILE_IDENTIFIER + '/' + Constant.PARTIAL_FILES)

**Comment by Ch00k** [comment]
After giving it a bit more thought it seems that's not that easy to prevent these kinds of errors. I could make the code a bit smarter and quote the option values that have spaces, but that would only work when the options are specified as an iterable (list, tuple etc.). Unfortunately there is no way to make it work when the options are a string (like it was in your case). Considering this, I think I will leave it to the end user to take care of quoting any values that contain spaces, at least for now. You must do it anyway when you run ffmpeg command on the command line.
