### ISSUE TITLE
RTMP Streaming

### ISSUE THREAD

**Issue by g3rd** [Ch00k/ffmpy#25]
Hello,

I have a few questions relating to RTMP streaming:

1. Is it possible to use **ffmpy** to live stream?
2. Is ``ff.run()`` blocking?
3. If it isn't blocking, how would you have it stop?

Thanks in advance!

**Comment by g3rd** [comment]
FYI. This is the command I am using:

```
ffmpeg 
  -f alsa -ac 1 -i plughw:1,0 
  -f v4l2 -s 1920x1080 
  -r 30 -input_format h264 
  -i /dev/video0 -vcodec copy 
  -preset veryfast -r 15 -g 30 
  -b:v 64k -ar 44100 -threads 6 
  -b:a 96k -bufsize 3000k 
  -f flv rtmp://user:pass@rtmp_url
```

**Comment by astroza** [comment]
@g3rd 
1) yes
2) ff.run is blocking. It uses python's popen.communicate().
3) Undefined

You have two options: 
A) Create another OS thread to call ffmpy.run() and kill if from main thread if necessary or 
B) Use my branch

I made a branch to take apart .run() into two methods: .start() and .wait()
https://github.com/astroza/ffmpy/blob/progress_support_v2/ffmpy.py
so, you could launch ffmpeg with start() and to poll the process with your own way. 

Additionally, if you use ff.run, it has a ring buffer for stderr for a proper memory usage and progress callback support

regards,

**Comment by g3rd** [comment]
@astroza Thanks! Going to give your branch a try!
