### ISSUE TITLE
Extract images from a video as numpy

### ISSUE THREAD

**Issue by srikanthsridar** [Ch00k/ffmpy#28]
Hello Andrii Yurchuk,
 Is it possible to use ffmpeg extracted frames in jpg to numpy using FFMPY?

**Comment by Ch00k** [comment]
It is of course possible. [Here](http://www.bugcodemaster.com/article/extract-images-frame-frame-video-file-using-ffmpeg) is a writeup on how to convert a video to a sequence of frames. After you've done that you can read your frames with e.g. [pillow](https://pillow.readthedocs.io/en/latest/handbook/tutorial.html)
