### ISSUE TITLE
ffmpy.FFmpeg output

### ISSUE THREAD

**Issue by Ungaminga** [Ch00k/ffmpy#29]
Hello, i'm using ffmpy on Windows. And i got no output in ffmpeg window, when i run my program. I used no modifications due to manual, like this:
`ff = ffmpy.FFmpeg(inputs=inputs, outputs={output:None})`
`ff.run()`
![image](https://user-images.githubusercontent.com/143675/36475009-0ebee7de-1702-11e8-834e-9e119ceee234.png)

I assume, this is regual question you got, but i failed to find an answer. Please give me ready-to-work solution. Hope i sounded not mean, it's about lack of languague skills.

**Comment by Ch00k** [comment]
The error you get is most probably caused by an incorrect command line you supply to ffmpeg. What happens if you copy the complete ffmpeg command and run it in a terminal? Do you also get an error?

**Comment by Ungaminga** [comment]
There are no error at all but empty black screen i got in console, as you see.
It's not a problem for me anymore, cause i switched to [moviepy](https://github.com/Zulko/moviepy).
