### ISSUE TITLE
Unable to Import FFmpeg

### ISSUE THREAD

**Issue by ghost** [Ch00k/ffmpy#3]
from ffmpy import FFmpeg

I have added both the ffmpeg bin and the ffmpeg exe to my system PATH, but my program keeps showing:

ImportError: cannot import name 'FFmpeg'

**Comment by Ch00k** [comment]
There is some incompatibility between how the code looks like in current master and in 0.0.6 (which is what installed from PyPI). In order to import you need to do `from ffmpy.ffmpeg import FFmpeg`.

**Comment by Ch00k** [comment]
This has now been resolved. PyPI now has the latest version available.
