### ISSUE TITLE
Multiple inputs result in single output copied.

### ISSUE THREAD

**Issue by Hritik14** [Ch00k/ffmpy#30]
```
	inputs={src+"/"+file:None for file in files}
	outputs={dst+"/"+file: '-vf transpose=clock' for file in files}

	ff = FFmpeg(
			inputs=inputs,
			outputs=outputs
			)
```
Expected: Every input file gets converted to corresponding output file.
I thought the API supports this because the variable is named `inputs` (though the ffmpeg binary doesn't)
But it is not supported and results in multiple files with same contents. 
This is very confusing and should be mentioned on the wiki.

**Comment by Ch00k** [comment]
You have to specify which input goes to which output with the `-map` option. This works for me, and creates two different output files.

```
ff = FFmpeg(
    inputs={
        '/home/ay/tmp/sample-1.mp4': None,
        '/home/ay/tmp/sample-2.mp4': None
    },
    outputs={
        '/home/ay/tmp/sample-1-out.mp4': '-map 0 -vf transpose=clock',
        '/home/ay/tmp/sample-2-out.mp4': '-map 0 -vf transpose=clock'
    }
)
ff.run()
```
