### ISSUE TITLE
How to use ffmpy to check videos for corruption?

### ISSUE THREAD

**Issue by jainal09** [Ch00k/ffmpy#36]
Hi i am  using FFmpeg on huge data set of videos and I might have some damaged videos in it?
Typically through the command line, I would do something like 
`ffmpeg -v error -i 3.mp4 -f null - &> test15.log`

But how can I do this through the python library?

**Comment by Ch00k** [comment]
Something like this should do what you want:

```python
ff = FFmpeg(
    global_options='-v error',
    inputs={'/tmp/sample-corrupted.mp4': None},
    outputs={'-': '-f null'},
)

try:
    ff.run(stdout=subprocess.PIPE, stderr=subprocess.PIPE)
except FFRuntimeError as e:
    print("The file is corrupted")
    print(e.stderr)
```
