### ISSUE TITLE
cannot find 'ffmpeg' when using PyCharm on macOS within conda environment

### ISSUE THREAD

**Issue by maruibin** [Ch00k/ffmpy#37]
When I called `ff.run()` in PyCharm on MacOS Catalina within conda environment, I got this error:
```python
Traceback (most recent call last):
  File "/Users/myname/.conda/envs/xiaoetong/lib/python3.7/site-packages/ffmpy.py", line 95, in run
    stderr=stderr
  File "/Users/myname/.conda/envs/xiaoetong/lib/python3.7/subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "/Users/myname/.conda/envs/xiaoetong/lib/python3.7/subprocess.py", line 1551, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'ffmpeg': 'ffmpeg'


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/myname/Documents/Projects/xiaoetong/ffmpy_test.py", line 8, in <module>
    ff.run()
  File "/Users/myname/.conda/envs/xiaoetong/lib/python3.7/site-packages/ffmpy.py", line 99, in run
    raise FFExecutableNotFoundError("Executable '{0}' not found".format(self.executable))
ffmpy.FFExecutableNotFoundError: Executable 'ffmpeg' not found

Process finished with exit code 1
```

This literally implies that either `ffmpeg` is not installed or the command is not added to path. However, I did install it, and I was able to call `ffmpeg` command successfully in the zsh terminal. I could also run that python script without error in terminal within exactly the same conda environment (and using exactly the same python interpreter).

The same code could also be run without error within the same conda environment in PyCharm on Windows 10.

Version I was using: python==3.7.5, ffmpeg==4.2, ffmpy==0.2.2, pycharm==2019.3.1(professional edition)

I also posted a question here: 
https://stackoverflow.com/questions/59586913/ffmpy-cannot-find-ffmpeg-when-running-in-pycharm-on-mac-using-conda-env

### For reproduction:
1. create python script as follow and add some sample data:
```python
import ffmpy

ff = ffmpy.FFmpeg(
     inputs={'input_dir/video.m3u8': ['-protocol_whitelist', 'crypto,file,http,https,tcp,tls']},
     outputs={'output_dir/ffmpy_test.mp4': None}
)
print(ff.cmd)
ff.run()
```

2. create conda environment, install ffmpeg, ffmpy

3. run that python script in PyCharm within that conda environment

**Comment by Ch00k** [comment]
Looks to me like PyCharm does not respect the PATH setting you have set in Zsh. Running `which ffmpeg` should show the absolute path the `ffmpeg` executable is located. I am not that familiar with PyCharm, but there should be a way to check the `PATH` that it uses, and see if `ffmpeg` directory is in it.
As a crude workaround you could always symlink `ffmpeg` in `/usr/bin`, which is usually always in `PATH`.
