### ISSUE TITLE
Deprecation warning due to invalid escape sequences

### ISSUE THREAD

**Issue by tirkarthi** [Ch00k/ffmpy#39]
Deprecation warning due to invalid escape sequences. Using raw strings or escaping them again helps in resolving this. Check https://github.com/asottile/pyupgrade/ for automatic fix of this.

```
find . -iname '*.py' | grep -Ev 'rdf4|tool|doc' | xargs -P4 -I{} python3.8 -Wall -m py_compile {}
./tests/test_cmd_compilation.py:84: DeprecationWarning: invalid escape sequence \:
  "timecode='09\:57\:00\:00': "
```

**Comment by Ch00k** [comment]
Fixed in https://github.com/Ch00k/ffmpy/pull/40
