### ISSUE TITLE
concatenate videos

### ISSUE THREAD

**Issue by anupamme** [Ch00k/ffmpy#4]
I have to concatenate multiple videos. I can do this on shell by following instructions at:

https://trac.ffmpeg.org/wiki/Concatenate

But I am not able to find api for concatenate in ffmpy.

Am I missing something or in current implementation concatenate is not done yet?

**Comment by Ch00k** [comment]
@anupamme ffmpy should support anything FFmpeg command line supports In your specific case you could try something like this:
```python
ffmpy.FFmpeg(
    inputs={"'concat:file1.ts|file2.ts'": None},
    outputs={'output.ts': '-c copy -bsf:a aac_adtstoasc'}
)
```
Let me know if that helps.

**Comment by Ch00k** [comment]
Closing assuming the above approach worked.
