### ISSUE TITLE
Can you add support for FFMPEG NVENC conversions?

### ISSUE THREAD

**Issue by githubtrip** [Ch00k/ffmpy#44]
The script is wonderful but a bit slow, can you add support for Nvidea FFmpeg Cuda Nvenc conversion?
Here's a link which might be useful - Zulko/moviepy#1014

**Comment by Ch00k** [comment]
As far as I can see from the response in https://github.com/Zulko/moviepy/issues/1014, all you have to do is use `global_options=['-hwaccel', 'cuvid']`. The you can use `codec='h264_nvenc'` in your `outputs` argument.
