### ISSUE TITLE
Color palette for gif

### ISSUE THREAD

**Issue by jonnymaserati** [Ch00k/ffmpy#46]
Hi there!

Is it possible to first do a color palette run when generating a .gif conversion? Currently the default generates a sort of bi-color .gif.

If I run ffmpeg from the terminal with this first:
```
ffmpeg -i input.mp4 -vf palettegen palette.png
```
And then:
```
ffmpeg -i input.mp4 -i palette.png -lavfi "paletteuse" output.gif
```
Then I get the desired result. Can this be emulated in `ffmpy`?

**Comment by Ch00k** [comment]
These are two different ffmpeg commands, so you would have to also run `ffmpy` twice to achieve what you want.
