### ISSUE TITLE
Get ffmpy progress?

### ISSUE THREAD

**Issue by midn1** [Ch00k/ffmpy#5]
Is it possible to get the video-conversion progress in ffmpy? Like from 0 to 100 or "timecode"/"video length"

**Comment by Ch00k** [comment]
@lvivtotoro You could try passing `global_options='-v quiet -stats'`. This shows progress based on the number of frames the input file has.
If this is not what you are after, please be a bit more specific in your description.

**Comment by lvivtotoro** [comment]
@Ch00k I need something similar to an async callback function that gives me the progress of the video conversion

**Comment by astroza** [comment]
https://github.com/Ch00k/ffmpy/issues/23

**Comment by Ch00k** [comment]
Closing in favor of #23
