### ISSUE TITLE
Allow an option to overwrite the existing file

### ISSUE THREAD

**Issue by WodenWang820118** [Ch00k/ffmpy#52]
First, thank you for the awesome wrapper to make the coding easier.
I am wondering if there's a way to overwrite the existing file automatically (or say yes directly to the command line). For now, I need to delete the file first, then execute the script. Thanks.

**Comment by Ch00k** [comment]
There is a `-y` global option that allows you to overwrite output files without confirmation: https://ffmpeg.org/ffmpeg.html#Main-options

**Comment by WodenWang820118** [comment]
Is it possible in the code? I mean something like:
```
import ffmpy
ff = ffmpy.FFmpeg(
inputs={'input.mp4': None},
outputs={'output.avi': None, 'overwrite': 'yes'}
)
ff.run()
```

Or, how could I code it properly to overwrite it? Thanks.

Sincerely,

**Comment by Ch00k** [comment]
Of course. Try this:

```python
ff = ffmpy.FFmpeg(
    global_options=['-y'],
    inputs={'input.mp4': None},
    outputs={'output.avi': None}
)
```

**Comment by WodenWang820118** [comment]
Thanks!!! It works like a charm.
