### ISSUE TITLE
Use FFProbe to Get Info From File

### ISSUE THREAD

**Issue by jjbaker4** [Ch00k/ffmpy#57]
Specifically, I am trying to get various pieces of info from ffprobe. Calling FFprobe.run() does not return all of the same information as running ffprobe from the cli. 

Running from CLI gets me data such as:
  Duration: 00:00:06.37, start: 0.000000, bitrate: 2812 kb/s
  Stream #0:0[0x1](und): Video: h264 (High) (avc1 / 0x31637661), yuv420p(progressive), 1280x720 [SAR 1:1 DAR 16:9], 2096 kb/s, 30 fps, 30 tbr, 15360 tbn (default)
    Metadata:
      handler_name    : VideoHandler
      vendor_id       : [0][0][0][0]
  Stream #0:1[0x2](und): Audio: aac (LC) (mp4a / 0x6134706D), 48000 Hz, stereo, fltp, 192 kb/s (default)
    Metadata:
      handler_name    : SoundHandler
      vendor_id       : [0][0][0][0]
Which includes stuff like video stream fps, duration, total bitrate, video stream bitrate, audio stream bitrate, audio stream codec.

The output from FFProbe.run() is missing this information. Is there a way to get the more detailed output that the cli command provides?
Here is my code currently:
`
source = os.path.join('d:\\', 'capstone', 'test_vids', 'input_jesse.mp4')
    ff_probe = ffmpy.FFprobe(
        inputs={source: None},
        global_options='-print_format json -show_format -show_streams'
    )
    metadata = ff_probe.run(stdout=subprocess.PIPE)
    print(metadata)
`

Update: My apologies. I'm not sure how to add code to this so it will display properly. Here is an image of that snippet.
![image](https://user-images.githubusercontent.com/62239223/161312363-4bc2e455-6b3a-404a-ac8f-2bf0c3e3ac7b.png)

**Comment by Ch00k** [comment]
It could be that this information is going into STDOUT. Try running it like this:

```python
metadata = ff_probe.run(stdout=subprocess.PIPE, stderr=subprocess.PIPE)
```

**Comment by Ch00k** [comment]
[Here](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks) you can read about how to insert code blocks in GitHub issues.
