### ISSUE TITLE
pipe:0: Invalid data found when processing input

### ISSUE THREAD

**Issue by ataubruno** [Ch00k/ffmpy#64]
I have this problem, I can't find a solution. I tried to do it through Command Prompt

usage: streamlink [OPTIONS] <URL> [STREAM]
streamlink: error: argument -o/--output: expected one argument
pipe:0: Invalid data found when processing input

C:\Windows\System32>

**Comment by Ch00k** [comment]
This error does not seem to be related to ffmpy.
