### ISSUE TITLE
Can't install on Python 3.10 - Windows 11

### ISSUE THREAD

**Issue by WASasquatch** [Ch00k/ffmpy#65]
```
PS C:\ComfyUI_windows_portable\python_embeded> ./python -s -m pip install ffmpy
Collecting ffmpy
  Using cached ffmpy-0.3.0.tar.gz (4.8 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\jorda\AppData\Local\Temp\pip-install-xxpmvq8x\ffmpy_14f9e068f9a54218b76e7156b7c315f8\setup.py", line 4, in <module>
          from ffmpy import __version__
      ModuleNotFoundError: No module named 'ffmpy'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

**Comment by ellementul** [comment]
I can't too

**Comment by dminGod** [comment]
I was able to get it to install -- what I did was:
- Download the file from : https://pypi.org/project/ffmpy/#files
- Extract the code
- Change the code in the setup.py to comment out the import of the `ffmpy` module (line 4, `#from ffmpy import __version__`
- Change the version to the actual version using string (line 8) `version="0.3.0",`
- `cd <path where you downloaded the ffmpy code>`
- Use the python environment / binary where you want to install it and run `setup.py`: <br/>
`<your python path> setup.py`

This should install the `ffmpy`

**Comment by WASasquatch** [comment]
Not really suitable for production environments or distributed packages
relying on ffmpy. I had to switch over to openvc python.

**Comment by Ch00k** [comment]
The project has been moved to Poetry, which no longer tries to import parts of the package it is installing. Please see if thise has fixed the installation issue for you. The latest version at the moment in 0.4.0.
