### ISSUE TITLE
Cant install on python 3.12

### ISSUE THREAD

**Issue by mkarimdev** [Ch00k/ffmpy#73]
`pip install ffmpy
Collecting ffmpy
  Using cached ffmpy-0.3.2.tar.gz (5.5 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [1 lines of output]
      ERROR: Can not execute `setup.py` since setuptools is not available in the build environment.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.`

**Comment by Ch00k** [comment]
Python 3.12 does not bundle setuptools anymore (see https://github.com/python/cpython/issues/95299), so you'd have to install it manually with `pip install setuptools` before you install `ffmpy`.
I should look into switching the project to something like Poetry.
