### ISSUE TITLE
Error when installing to to update to setuptools

### ISSUE THREAD

**Issue by NoahKamara** [Ch00k/ffmpy#75]
The update removed the test command. More info here. Might come back later to fix this 

https://github.com/pypa/setuptools/issues/4519

**Comment by mikeshi80** [comment]
duplicated with #74

**Comment by EuDs63** [comment]
This bug arises from changes made to `setuptools.command.test` in the 72.0.0 update of `setuptools`. For more details, refer to the [setuptools · PyPI](https://pypi.org/project/setuptools/#history) page. One of the dependencies used in this repository, [Ch00k/ffmpy: Pythonic interface for FFmpeg/FFprobe command line](https://github.com/Ch00k/ffmpy), utilizes `setuptools.command.test`.

As a temporary solution, I forked the project and removed the relevant code to ensure it runs smoothly. You can use the following command to install the modified version:

```sh
pip install git+https://github.com/EuDs63/ffmpy.git
```

**Comment by Ch00k** [comment]
This is now fixed in 0.3.3
