### ISSUE TITLE
FFprobe.run() prints results but doesn't return them.

### ISSUE THREAD

**Issue by fleischie** [Ch00k/ffmpy#8]
Hello.

Some useful information I guess:
- Python 3.5.2,
- ffmpy 0.2.0 (the "usually" part was written on 0.1.0, where it still works as expected).

I usually am running `ffmpy.FFprobe` to get the dimensions of a video (amongst other things):

```
import ffmpy
ff = ffmpy.FFprobe(inputs={
    '': ('-v error -show_entries stream=width,height '
         '-of default=noprint_wrappers=1:nokey=1 '
         '{video_path}').format(video_path=video_path)
})
ff.run()
```

The result has been `(640,320)` or similar before but now it only produces `(None,None)` and prints out the result:

```
>>> result = ff.run()
640
360
>>> print(result)
(None, None)
```

I could intercept the stdout and use the result from there (I guess.... because why shouldn't I? Workarounds ftw. 😄 ) but I thought I first ask/post my issue here to understand know, whether this is intended behaviour? 😃 

I'm available for feedback/discussion on this. 😉

**Comment by Ch00k** [comment]
With 0.2.0 release I changed the way stdout/stderr is displayed and returned. The `run` method now has two new arguments: `stdout` and `stderr` which specify stdout and stderr redirection respectively. By default they are both set to `None` which means no redirection: everything is printed into the running terminal. You can also use `subprocess.PIPE` as the value for `stdout` to get stdout as the return value. I think this is what you want. Check out the doc [here](http://ffmpy.readthedocs.io/en/latest/ffmpy.html) and the last example [here](http://ffmpy.readthedocs.io/en/latest/examples.html) for more explanation.
Let me know if that helps :)

**Comment by fleischie** [comment]
@Ch00k I never answered, sorry about this. But your description was most helpful. :bowing_man:
