### ISSUE TITLE
Bug: ffmpy breaks all typedefs in some situations

### ISSUE THREAD

**Issue by patrickhulce** [Ch00k/ffmpy#82]
Hi there 👋  Great package thanks for your work :)

I recently spent several hours dealing with an issue in VSCode where all type annotations were broken and the root cause was the `py.typed` file that this package puts into the root of `site-packages` (see https://github.com/microsoft/pylance-release/issues/4844#issuecomment-2491843821).

It definitely seems accidental to express typedef readiness for _all_ site packages. Would you be willing to restructure this into a `ffmpy/` directory package instead of the single file, so this doesn't happen to others?

**Comment by Ch00k** [comment]
Ouch, that is a nasty one 😞 Great find though, thank you for reporting it. I'll see what I can do.

**Comment by Ch00k** [comment]
@patrickhulce I just released 0.5.0, which, among other housekeeping changes, moves the code into a package, along with `py.typed` file. Please have a look if this addresses the issue for you.
