### ISSUE TITLE
print_format parameter throws error

### ISSUE THREAD

**Issue by busla** [Ch00k/ffmpy#9]
Thanks for contributing 👍 

Using this:

```
ff_probe = ffmpy.FFprobe(
    inputs = {
        'myurl': None,
    },
    global_options = [
        '-print_format json',
        '-show_format',
        '-show_streams',
    ]
)
```

Runs this command:
`ffprobe "-print_format json" -show_format -show_streams -i http://myurl.me`

And gives me this error:
`Failed to set value '-show_format' for option 'print_format json': Option not found`

As you can see the *print_format json* gets wrapped in double quotes.

**Comment by Ch00k** [comment]
@busla Thanks for reporting! I can see why and where it fails, will try to find the best solution to fix that. In the meantime, a quick workaround would be to use a single string for `global_options`.
```
ff_probe = ffmpy.FFprobe(
    inputs = {'myurl': None},
    global_options = '-print_format json -show_format -show_streams'
)
```

**Comment by busla** [comment]
Great!

Thanks :-)
